In [1]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv(r'E:\100 Days of Machine Learning - CampusX\Datasets\placement.csv')

In [5]:
df.head()

   Unnamed: 0  cgpa     iq  placement
0           0   6.8  123.0          1
1           1   5.9  106.0          0
2           2   5.3  121.0          0
3           3   7.4  132.0          1
4           4   5.8  142.0          0

In [6]:
df.shape

(100, 4)

In [7]:
df = df.iloc[:, 1: ]

In [8]:
df.head()

   cgpa     iq  placement
0   6.8  123.0          1
1   5.9  106.0          0
2   5.3  121.0          0
3   7.4  132.0          1
4   5.8  142.0          0

#### Steps
0. Preprocess + EDA + Feature Selection
1. Extract input and output data
2. Scale the values
3. Train test split
4. Train the model
5. Evaluate the model/ model selection
6. Deploy the mode